// AUTO-GENERATED by scripts/gen-examples.mjs — do not edit.
import type { ComponentType } from "react"
import C0 from "./examples/alert-dialog-demo"
import C1 from "./examples/button-demo"
import C2 from "./examples/button-group-demo"
import C3 from "./examples/button-group-showcase"
import C4 from "./examples/button-showcase"
import C5 from "./examples/card-demo"
import C6 from "./examples/card-tasklist"
import C7 from "./examples/combobox-demo"
import C8 from "./examples/combobox-showcase"
import C9 from "./examples/dialog-demo"
import C10 from "./examples/dialog-showcase"
import C11 from "./examples/field-demo"
import C12 from "./examples/field-showcase"
import C13 from "./examples/input-demo"
import C14 from "./examples/input-group-demo"
import C15 from "./examples/input-group-showcase"
import C16 from "./examples/input-showcase"
import C17 from "./examples/radio-group-demo"
import C18 from "./examples/radio-group-showcase"
import C19 from "./examples/select-demo"
import C20 from "./examples/select-showcase"
import C21 from "./examples/slider-demo"
import C22 from "./examples/slider-showcase"
import C23 from "./examples/slider-sizes"
import C24 from "./examples/slider-variants"
import C25 from "./examples/sonner-demo"
import C26 from "./examples/sonner-showcase"
import C27 from "./examples/stepper-demo"
import C28 from "./examples/stepper-showcase"
import C29 from "./examples/switch-demo"
import C30 from "./examples/switch-showcase"

export const examples: Record<string, ComponentType> = {
  "alert-dialog-demo": C0,
  "button-demo": C1,
  "button-group-demo": C2,
  "button-group-showcase": C3,
  "button-showcase": C4,
  "card-demo": C5,
  "card-tasklist": C6,
  "combobox-demo": C7,
  "combobox-showcase": C8,
  "dialog-demo": C9,
  "dialog-showcase": C10,
  "field-demo": C11,
  "field-showcase": C12,
  "input-demo": C13,
  "input-group-demo": C14,
  "input-group-showcase": C15,
  "input-showcase": C16,
  "radio-group-demo": C17,
  "radio-group-showcase": C18,
  "select-demo": C19,
  "select-showcase": C20,
  "slider-demo": C21,
  "slider-showcase": C22,
  "slider-sizes": C23,
  "slider-variants": C24,
  "sonner-demo": C25,
  "sonner-showcase": C26,
  "stepper-demo": C27,
  "stepper-showcase": C28,
  "switch-demo": C29,
  "switch-showcase": C30,
}
