// gen-springs.mjs — generate CSS linear() easing strings from Apple-style
// spring parameters (damping ratio + response), plus the raw numbers a JS
// spring library (Motion) consumes. Pure Node, no dependencies.
//
//   node scripts/gen-springs.mjs          # prints the CSS block to stdout
//
// The two forms of each preset (the linear() curve and the damping/response
// numbers) describe the SAME physical spring, so CSS-driven and JS-driven
// motion match. Do not hand-edit the emitted linear() values — regenerate.
//
// Model: a unit step of a damped harmonic oscillator settling 0 -> 1.
//   omega   = 2*pi / response        (natural angular frequency)
//   zeta    = damping                (damping ratio; 1 = critical, <1 = bouncy)
//   zeta  < 1 (underdamped):
//     x(t) = 1 - e^(-zeta*omega*t) * (cos(wd*t) + (zeta*omega/wd)*sin(wd*t))
//     wd   = omega*sqrt(1 - zeta^2)  (damped frequency)
//   zeta == 1 (critically damped):
//     x(t) = 1 - e^(-omega*t) * (1 + omega*t)
//
// Underdamped springs overshoot (x > 1) then settle — that overshoot is
// intentional for the "bounce" preset, and linear() supports values > 1.

const PRESETS = [
  { name: "default", damping: 1.0, response: 0.4, note: "critically damped, no overshoot — most UI" },
  { name: "drawer", damping: 0.8, response: 0.3, note: "sheets / drawers" },
  { name: "bounce", damping: 0.8, response: 0.4, note: "deliberate overshoot for momentum-carried gestures" },
];

const STOPS = 24; // sample count → linear() control points

function springPosition(t, damping, response) {
  const omega = (2 * Math.PI) / response;
  if (damping >= 1) {
    // critically damped (treat >1 as critical for our presets)
    return 1 - Math.exp(-omega * t) * (1 + omega * t);
  }
  const zeta = damping;
  const wd = omega * Math.sqrt(1 - zeta * zeta);
  return (
    1 -
    Math.exp(-zeta * omega * t) *
      (Math.cos(wd * t) + ((zeta * omega) / wd) * Math.sin(wd * t))
  );
}

// Find the settle time: first time after which the spring stays within
// `tol` of 1 for the rest of a scan window. Guarantees the emitted curve
// ends at (or extremely near) 1 so the transition lands exactly on target.
function settleTime(damping, response, tol = 0.001) {
  const omega = (2 * Math.PI) / response;
  // Envelope decays like e^(-zeta*omega*t); solve for when it's below tol.
  const zeta = Math.min(damping, 1);
  const tEnv = -Math.log(tol) / (zeta * omega);
  // For underdamped, extend a little so a late overshoot peak is captured.
  const pad = damping < 1 ? response * 0.5 : 0;
  return tEnv + pad;
}

function linearFor(damping, response) {
  const T = settleTime(damping, response);
  const points = [];
  for (let i = 0; i <= STOPS; i++) {
    const t = (i / STOPS) * T;
    let x = springPosition(t, damping, response);
    // clamp tiny numerical noise at the ends
    if (i === 0) x = 0;
    if (i === STOPS) x = 1;
    points.push([i / STOPS, x]);
  }
  // Emit: first point implicit position 0%, last 100%. Include explicit
  // percentages so the curve is unambiguous. Round to 4 significant places.
  const body = points
    .map(([p, x], i) => {
      const val = round(x);
      if (i === 0) return `${val}`;
      if (i === STOPS) return `${val} 100%`;
      return `${val} ${Math.round(p * 100)}%`;
    })
    .join(", ");
  return `linear(${body})`;
}

function round(n) {
  // 4 significant decimals, strip trailing zeros
  return parseFloat(n.toFixed(4)).toString();
}

// Motion mapping: bounce ≈ 1 - damping (clamped), duration = response.
function motionBounce(damping) {
  return Math.max(0, Math.min(1, 1 - damping));
}

function emitCss() {
  const lines = [];
  lines.push(
    "  /* Spring motion tokens — GENERATED by scripts/gen-springs.mjs from (damping, response)."
  );
  lines.push(
    "     Do not hand-edit the linear() values; regenerate. Theme-independent (physics, not"
  );
  lines.push(
    "     color) so defined once here. `-damping`/`-response`/`-bounce` feed a JS spring lib"
  );
  lines.push(
    "     (Motion: bounce ≈ 1 - damping, duration = response). The curve is the timing-function"
  );
  lines.push(
    "     (shape, set by the damping ratio); pair it with the matching `-duration` for a"
  );
  lines.push(
    "     complete CSS transition. Two presets with equal damping share a curve and differ"
  );
  lines.push("     only in duration. */");
  for (const p of PRESETS) {
    lines.push(`  /* ${p.name}: damping ${p.damping}, response ${p.response} — ${p.note} */`);
    lines.push(`  --acr-spring-${p.name}: ${linearFor(p.damping, p.response)};`);
    lines.push(`  --acr-spring-${p.name}-duration: ${p.response}s; /* CSS transition-duration */`);
    lines.push(`  --acr-spring-${p.name}-damping: ${p.damping};`);
    lines.push(`  --acr-spring-${p.name}-response: ${p.response};`);
    lines.push(
      `  --acr-spring-${p.name}-bounce: ${round(motionBounce(p.damping))}; /* Motion bounce */`
    );
  }
  return lines.join("\n");
}

// cubic-bezier fallbacks for browsers without linear() easing support.
const FALLBACKS = {
  default: "cubic-bezier(0.22, 1, 0.36, 1)",
  drawer: "cubic-bezier(0.32, 0.72, 0, 1)",
  bounce: "cubic-bezier(0.34, 1.56, 0.64, 1)",
};

function emitFallback() {
  const lines = [];
  lines.push("@supports not (transition-timing-function: linear(0, 1)) {");
  lines.push("  :root {");
  for (const p of PRESETS) {
    lines.push(`    --acr-spring-${p.name}: ${FALLBACKS[p.name]};`);
  }
  lines.push("  }");
  lines.push("}");
  return lines.join("\n");
}

console.log(emitCss());
console.log("");
console.log("/* fallback block (place outside :root) */");
console.log(emitFallback());
